start /wait p2bin sinistar.p sinistar_rom_1-b_16-3004-53.1d -r $0000-$0FFF
start /wait p2bin sinistar.p sinistar_rom_2-b_16-3004-54.1c -r $1000-$1FFF
start /wait p2bin sinistar.p sinistar_rom_3-b_16-3004-55.1a -r $2000-$2FFF
start /wait p2bin sinistar.p sinistar_rom_4-b_16-3004-56.2d -r $3000-$3FFF
start /wait p2bin sinistar.p sinistar_rom_5-b_16-3004-57.2c -r $4000-$4FFF
start /wait p2bin sinistar.p sinistar_rom_6-b_16-3004-58.2a -r $5000-$5FFF
start /wait p2bin sinistar.p sinistar_rom_7-b_16-3004-59.3d -r $6000-$6FFF
start /wait p2bin sinistar.p sinistar_rom_8-b_16-3004-60.3c -r $7000-$7FFF
start /wait p2bin sinistar.p sinistar_rom_9-b_16-3004-61.3a -r $8000-$8FFF
start /wait p2bin sinistar.p sinistar_rom_10-b_16-3004-62.4c -r $E000-$EFFF
start /wait p2bin sinistar.p sinistar_rom_11-b_16-3004-63.4a -l 00 -r $F000-$FFFF